services:
  - type: web
    name: puppy-spa-api
    env: node
    region: frankfurt
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://puppy-spa-beta.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: puppy_spa_db
          property: connectionString

databases:
  - name: puppy_spa_db
    region: frankfurt
    plan: free 